version: 2
jobs:
  build:
    docker:
      - image: lelandjansen/onchange:0.0.1
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            mkdir build
            cd build
            cmake ../src && cmake ../src
            make -j2

